# Generated by Django 4.0.5 on 2022-06-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='active',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customers',
            name='salesrepemployeenumber',
            field=models.ForeignKey(blank=True, db_column='salesRepEmployeeNumber', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_rep', to='api.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='reportsto',
            field=models.ForeignKey(blank=True, db_column='reportsTo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manages', to='api.employees'),
        ),
    ]
